# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Complexe
                                 A QGIS plugin
 Assistant complexe
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-27
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Gérôme PECHEUR (IGN)
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import webbrowser

from qgis.PyQt.QtCore import QObject, QEvent, QTimer
from qgis.PyQt.QtGui import QIcon, QPixmap, QStandardItem, QStandardItemModel,QIntValidator
from qgis.PyQt.QtWidgets import  QListWidgetItem, QPushButton, QListView, QVBoxLayout, \
    QAbstractItemView, QTableView, QApplication,QLabel,QLineEdit
from qgis.PyQt.uic import loadUi
import json

from .constantes import *
from .mapping_version import *

# Initialize Qt resources from file resources.py
# Import the code for the dialog

SEPARATION_TOOLTIP = "\t\U0001F846\t"

import os.path
from .layout_fluide import *

class FiltreClicDroit(QObject):
    def __init__(self, class_parent):
        super().__init__()
        self.class_parent = class_parent

    def eventFilter(self,obj,event):
        if event.type() == QEvent.MouseButtonPress and event.button() == RightButton:
            self.class_parent.show_dlg_config_btn(obj)
            return True  # on consomme l’événement (empêche le clic normal).

        if event.type() == QEvent.MouseButtonPress and event.button() == LeftButton:
            if isinstance(obj, QPushButton):
                self._dragging = False
                self.widget_avant_move = obj
                self._press_pos = event.pos()

        if event.type() == QEvent.MouseMove:
            if getattr(self, "_press_pos", None):
                if (event.globalPos() - self._press_pos).manhattanLength() > QApplication.startDragDistance():
                    if isinstance(obj, QPushButton):
                        self._dragging = True
                        self.class_parent.init_fantome_btn(event,obj)

        if event.type() == QEvent.MouseButtonRelease and event.button() == LeftButton:
            if getattr(self, "_dragging", False):
                widget_apres_move = QApplication.widgetAt(event.globalPos())
                if isinstance(obj, QPushButton):
                    self.class_parent.relache_clic_gauche_btn(self.widget_avant_move, widget_apres_move)
            self._dragging = False
            self._press_pos = None
            self.widget_avant_move = None
            self.class_parent._ghost.hide()
        return False

class JeuxAttributs:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):

        # =====================================================
        # image fantôme qui suit la souris lors du drag and drop des boutons
        self._ghost = QLabel(None)
        self._ghost.setWindowFlags(ToolTip | FramelessWindowHint)
        self._ghost.setScaledContents(True)
        self._ghost.setStyleSheet("""
                    background-color: rgb(30, 144, 255);  /* bleu semi-transparent */
                    border: 1px solid blue;
                    padding: 1px;
                """)
        self._ghost.hide()

        # choix de l'icône
        self.button_ok = None
        self.listview = None

        self.valeur_btn_sel = None
        self.sstype_btn_sel = None

        self.dlg_sel_champ_val = None
        self.dlg_config_btn = None
        self.dlg = None
        self.dlg_icon = None

        self.clicked_button = None

        self.iface = iface
        self.layer = None
        self.dico_layer_attrval = {}
        self.liste_filtres = []
        self.model = None
        self.pathiconbtnclicked = None
        self.pathjson = os.path.join(os.path.dirname(__file__),"config", "config_btn.json")
        self.pathicon_config = os.path.join(os.path.dirname(__file__), "icons", "config.png")
        self.pathicon_interface = os.path.join(os.path.dirname(__file__), "icons", "icon_principal.png")
        self.path_repicon_btn = os.path.join(os.path.dirname(__file__),"config", "icons_btn")

        self.layout_boutons = None

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    def init_fantome_btn(self, event, obj):
        pix = obj.grab().scaled(obj.width(), obj.height())
        self._ghost.setPixmap(pix)
        self._ghost.move(event.globalPos() + QPoint(1, 1))
        self._ghost.show()

    def relache_clic_gauche_btn(self, obj, obj_sous_mouse):
        pos_init = self.getposition_btn(obj)
        pos_final = self.getposition_btn(obj_sous_mouse)
        # si la position est en dehors du layout, on quitte
        if pos_init is None or pos_final is None:
            return
        self.deplace_btn(pos_init, pos_final)

    def getposition_btn(self, obj):
        return self.layout_boutons.index_of_widget(obj)

    def on_apropos(self):
        dlgAProposDe = QDialog()
        loadUi(os.path.dirname(__file__) + "/aproposde.ui", dlgAProposDe)
        dlgAProposDe.setWindowFlags(WindowStaysOnTopHint | WindowCloseButtonHint)
        dlgAProposDe.setWindowTitle("A propos de...")
        dlgAProposDe.pushButtonAffichedoc.clicked.connect(self.affiche_doc)
        dlgAProposDe.exec()

    def affiche_doc(self):
        webbrowser.open("https://a_definir")

    def show_dlg_config_btn(self,btn):
        self.clicked_button = btn
        # recuperation des infos du bouton cliqué
        self.sstype_btn_sel = btn.property("sstype")
        self.valeur_btn_sel = btn.property("valeur")

        self.dlg_config_btn.setWindowTitle("Paramétrage des boutons et des actions associés")
        self.dlg_config_btn.setWindowFlags(WindowStaysOnTopHint | WindowCloseButtonHint)
        # le nom est récupéré à partir du tooltip
        # car si l'icône est renseigné le bouton perd son nom
        self.dlg_config_btn.lineEditNomBtn.setText(btn.text())

        # ****************NOM BOUTON*****************
        nom_btn = ""
        for item in self.dico_layer_attrval.get(self.layer.name(), []):
            if item.get("sous_type") == self.sstype_btn_sel and item.get("valeur") == self.valeur_btn_sel:
                # Exemple : mise à jour du nom du bouton
                nom_btn = item["nom_btn"]
                break
        self.dlg_config_btn.lineEditNomBtn.setText(nom_btn)

        # ****************ICONE**********************
        icon_str = ""
        for item in self.dico_layer_attrval.get(self.layer.name(), []):
            if item.get("sous_type") == self.sstype_btn_sel and item.get("valeur") == self.valeur_btn_sel:
                    # Exemple : mise à jour du nom du bouton
                    icon_str = item["icon"]
                    break
        self.dlg_config_btn.lineEdit_icone.setText(icon_str)
        path = os.path.join(self.path_repicon_btn,icon_str)
        pixmap = QPixmap(path)
        pixmap = pixmap.scaled(20, 20, KeepAspectRatio, SmoothTransformation)
        self.dlg_config_btn.label_icon_sel.setPixmap(pixmap)

        # ***************AUTRE VALEUR*********************
        autre_sstype_valeur = {}
        for item in self.dico_layer_attrval.get(self.layer.name(), []):
            if item.get("sous_type") == self.sstype_btn_sel and item.get("valeur") == self.valeur_btn_sel:
                # Exemple : mise à jour du nom du bouton
                autre_sstype_valeur = item["autre_valeur"]
                break
        model = self.dlg_config_btn.tableView_autre_valeur.model()
        # il faut vider le tableview avant d'ajouter
        model.clear()
        for sstype_autre, valeur_autre in autre_sstype_valeur.items():
            model.appendRow([QStandardItem(sstype_autre), QStandardItem(valeur_autre)])
        self.dlg_config_btn.tableView_autre_valeur.setColumnWidth(0, 150)
        self.dlg_config_btn.tableView_autre_valeur.setColumnWidth(1, 150)
        model.setHeaderData(0, Horizontal, "Sous type")
        model.setHeaderData(1, Horizontal, "Valeur")

        sstype_str = f"<span style='color: red'><b>{self.sstype_btn_sel}</b></span>"
        self.dlg_config_btn.label_ss_type.setText(sstype_str)
        valeur_str = f"<span style='color: red'><b>{self.valeur_btn_sel}</b></span>"
        self.dlg_config_btn.label_valeur.setText(valeur_str)
        self.dlg_config_btn.label_fleche.setText(SEPARATION_TOOLTIP)

        self.dlg_config_btn.labelAvertissement.setText("")

        try:
            self.dlg_config_btn.pushButton_choix_icon.clicked.disconnect()
        except TypeError:
            pass
        self.dlg_config_btn.pushButton_choix_icon.clicked.connect(lambda: self.choix_icone(self.sstype_btn_sel, self.valeur_btn_sel))
        self.dlg_config_btn.lineEditNomBtn.textChanged.connect(self.nom_btn_change)

        self.dlg_config_btn.exec()


    def suppr_ligne_tableview(self):
        # recuperation de la selection
        model = self.dlg_config_btn.tableView_autre_valeur.model()
        selection_model = self.dlg_config_btn.tableView_autre_valeur.selectionModel()
        # index des lignes selectionnées
        selected_indexes = selection_model.selectedRows()

        for index in selected_indexes:
            row = index.row()
            model.removeRow(row)

        # maj du dictionnaire
        self.clicked_button.toolTip()
        for item in self.dico_layer_attrval.get(self.layer.name(), []):
            if item.get("sous_type") == self.sstype_btn_sel and item.get("valeur") == self.valeur_btn_sel:
                # Exemple : mise à jour du nom du bouton
                item["autre_valeur"] = self.convert_tableview_to_dico()
                break
        self.save_json()

    def deplace_btn(self,old_position,new_position):
        dico_avant = self.dico_layer_attrval[self.layer.name()]

        # si on deplace sur le premier btn (configuration) on le place juste apres.
        if new_position == 0:
            new_position = 1

        # conversion en index Python (0-based)
        old_idx = old_position - 1
        new_idx = new_position - 1

        # retire élément déplacé de la liste et le stocke temporairement
        item = dico_avant.pop(old_idx)

        # si on déplace vers la droite,
        # le pop() a déjà décalé les indices
        if old_idx < new_idx:
            new_idx -= 1

        # insertion AVANT le bouton cible
        dico_avant.insert(new_idx, item)

        self.save_json()

        # actualisation interface
        # rafraîchissement de l'interface
        self.clear_layout(self.layout_boutons)
        self.liste_filtres = []
        self.initLayout()
        self.load_json()
        self.ajout_btn_from_json()

        self.dlg.adjustSize()

    def nom_btn_change(self):
        if self.dlg_config_btn.lineEditNomBtn.text() != "":
            self.dlg_config_btn.labelAvertissement.setText("")

    def valide_config_btn(self,sstype,valeur):
        # self.valide_nom_btn(sstype,valeur)
        self.valide_nom_et_icone(sstype, valeur)

        if self.dlg_config_btn.lineEditNomBtn.text() == "" and not self.pathiconbtnclicked:
            self.dlg_config_btn.labelAvertissement.setText("<span style='color: red'><b>Le bouton doit avoir un nom OU/ET une icône</b></span>")
            return

        self.save_json()
        self.clear_layout(self.layout_boutons)
        self.liste_filtres = []
        self.initLayout()
        self.load_json()
        self.ajout_btn_from_json()
        self.dlg_config_btn.close()

    def choix_autre_valeur(self):
        self.dlg_sel_champ_val_AUTRE.setWindowFlags(WindowStaysOnTopHint | WindowCloseButtonHint)
        self.dlg_sel_champ_val_AUTRE.comboBoxchamps.clear()
        self.dlg_sel_champ_val_AUTRE.listattributs.clear()
        self.init_combo_choix_champ(self.dlg_sel_champ_val_AUTRE)
        self.dlg_sel_champ_val_AUTRE.exec()

    def valide_nom_et_icone(self, sstype, valeur):
        for item in self.dico_layer_attrval.get(self.layer.name(), []):
            if item.get("sous_type") == sstype and item.get("valeur") == valeur:
                item["nom_btn"] = self.dlg_config_btn.lineEditNomBtn.text()
                item["icon"] = self.dlg_config_btn.lineEdit_icone.text().strip()
                break
            if not item["nom_btn"] and not item["icon"]:
                return False
        return True

    def valide_icone(self,sstype,valeur):
        # sauvegarde de l'icon le dictionnaire
        if self.pathiconbtnclicked:
            filico = os.path.basename(self.pathiconbtnclicked)
            self.dlg_config_btn.lineEdit_icone.setText(filico)
        else:
            filico = ""
        # ajout de l'icone dans le dictionnaire
        for item in self.dico_layer_attrval.get(self.layer.name(), []):
            if item.get("sous_type") == sstype and item.get("valeur") == valeur:
                # mise à jour de l'icône du bouton
                item["icon"] = filico
                # item["nom_btn"] = ""
                break


        # on actualise l'icône à afficher apres le nom de l'icône
        pixmap = QPixmap(self.pathiconbtnclicked)
        pixmap = pixmap.scaled(20, 20, KeepAspectRatio, SmoothTransformation)
        self.dlg_config_btn.label_icon_sel.setPixmap(pixmap)

    # on a choisi une icone
    def valide_dlg_icone(self,sstype,valeur):
        self.valide_icone(sstype, valeur)
        self.dlg_icon.close()

    def choix_icone(self,sstype,valeur):
        # interface
        self.dlg_icon = QDialog()
        self.dlg_icon.setWindowTitle("Choisir une icône...")
        self.dlg_icon.setWindowIcon(QIcon(self.pathicon_interface))
        self.dlg_icon.setWindowFlags(WindowStaysOnTopHint | WindowCloseButtonHint)
        layout = QVBoxLayout()
        self.listview = QListView()
        self.button_ok = QPushButton("Valider")
        layout.addWidget(self.listview)
        layout.addWidget(self.button_ok)
        self.dlg_icon.setLayout(layout)
        # self.button_ok.clicked.connect(lambda:self.valider_icone(sstype,valeur))
        self.button_ok.clicked.connect(lambda:self.valide_dlg_icone(sstype,valeur))

        self.init_listview_icones()

        self.dlg_icon.exec()

    def init_listview_icones(self):
        self.model = QStandardItemModel()
        self.listview.setModel(self.model)
        self.listview.setViewMode(QListView.IconMode)
        self.listview.setSelectionMode(QListView.SingleSelection)
        for filename in os.listdir(self.path_repicon_btn):
            if filename.lower().endswith(".ico"):
                path = os.path.join(self.path_repicon_btn, filename)
                # pixmap = QPixmap(path).scaled(30, 30)
                pixmap = QPixmap(path)
                icon = QIcon(pixmap)

                item = QStandardItem(icon, filename)
                item.setData(path)  # On garde le chemin complet
                item.setEditable(False)
                self.model.appendRow(item)

        self.listview.clicked.connect(self.get_icon_path_selected)

    def get_icon_path_selected(self, index):
        """Quand l'utilisateur clique sur une icône."""
        self.pathiconbtnclicked = self.model.itemFromIndex(index).data()

    # ajout de tous les champs possible dans le combobox
    def init_combo_choix_champ(self,dlg):
        self.layer = self.iface.activeLayer()
        for field in self.layer.fields():
            index = self.layer.fields().indexOf(field.name())
            widget_type = self.get_type_champ(index)
            if widget_type == "ValueMap":
                dlg.comboBoxchamps.addItem(field.name())
            elif widget_type == "TextEdit" and field.name() not in CHAMPS_IGNORE:
                print("field = ",field.name())
                dlg.comboBoxchamps.addItem(field.name())
                # print(f"Champ {field.name()} ignoré car type d’éditeur : {widget_type}")

    # initialise toutes les valeurs en fonction du champ sélectionné
    def init_list_valeur(self,champ,dlg):
        # pk faire ce test !!
        if champ == "":
            return
        list_sstype_val = self.get_sstype_valeur_from_dico(self.layer.name(),self.dico_layer_attrval)
        dlg.listattributs.clear()
        layer_field = self.layer.fields().field(champ)
        # Vérifier le type d’éditeur
        editor_setup = layer_field.editorWidgetSetup()
        valeurs_possibles = []

        # CAS TEXTEDIT -> une seule entrée éditable
        if editor_setup.type() == "TextEdit":
            print("champ = ",champ,"type textedit")
            item = QListWidgetItem("Saisir une valeur...")
            item.setFlags(item.flags() | Qt.ItemIsEditable | Qt.ItemIsEnabled | Qt.ItemIsSelectable)
            dlg.listattributs.addItem(item)
            return

        # CAS NORMAL (ValueMap etc.)
        for v in editor_setup.config().values():
            if isinstance(v, dict):
                valeurs_possibles.extend(v.values())
            elif isinstance(v, list):
                for elem in v:
                    if isinstance(elem, dict):
                        valeurs_possibles.extend(elem.values())
                    else:
                        valeurs_possibles.append(elem)
            elif isinstance(v, (str, int, float)):
                valeurs_possibles.append(v)

        for val in valeurs_possibles:
            item = QListWidgetItem(str(val))
            item.setCheckState(Unchecked)
            if dlg == self.dlg_sel_champ_val:
                if (champ,val) in list_sstype_val:
                    item.setCheckState(Checked)
            dlg.listattributs.addItem(item)
            if dlg == self.dlg_sel_champ_val_AUTRE:
                self.dlg_sel_champ_val_AUTRE.listattributs.itemChanged.connect(self.on_item_changed)

    def on_item_changed(self, changed_item):
        """Empêche d'avoir plusieurs cases cochées."""
        if changed_item.checkState():
            # Décoche toutes les autres
            for i in range(self.dlg_sel_champ_val_AUTRE.listattributs.count()):
                item = self.dlg_sel_champ_val_AUTRE.listattributs.item(i)
                if item is not changed_item and item.checkState():
                    item.setCheckState(0)

    def get_attrs_coches(self,dlg,coche = True):
        val_coche = []
        if coche:
            bcoche = Checked
        else:
            bcoche = Unchecked
        for i in range(dlg.listattributs.count()):
            item = dlg.listattributs.item(i)
            if item.checkState() == bcoche:
                val_coche.append(item.text())
        return val_coche

    def show_choix_attr_val(self):
        self.dlg_sel_champ_val.comboBoxchamps.clear()
        self.dlg_sel_champ_val.listattributs.clear()
        self.init_combo_choix_champ(self.dlg_sel_champ_val)
        self.dlg_sel_champ_val.setWindowFlags(WindowStaysOnTopHint | WindowCloseButtonHint)
        self.dlg_sel_champ_val.exec()

    def change_champ(self,dlg):
        dlg.listattributs.clear()
        champ = dlg.comboBoxchamps.currentText()
        self.init_list_valeur(champ,dlg)

    def get_type_champ(self,index):
        return self.layer.editorWidgetSetup(index).type()

    @staticmethod
    def clear_layout(layout):
        """Supprime tous les widgets d’un QLayout"""
        while layout.count():
            item = layout.takeAt(0)
            widget = item.widget()
            if widget is not None:
                widget.setParent(None)
                widget.deleteLater()
            elif item.layout():
                JeuxAttributs.clear_layout(item.layout())

    # ajout du bouton de paramétrage
    def initLayout(self):
        btn_add = QPushButton()
        btn_add.setIcon(QIcon(self.pathicon_config))
        btn_add.setFixedWidth(20)
        btn_add.setFixedHeight(20)
        # self.btn_add.setStyleSheet("background-color: lightblue;")
        btn_add.clicked.connect(self.show_choix_attr_val)

        self.layout_boutons.addWidget(btn_add)

        self.dlg.setLayout(self.layout_boutons)

    def get_sstype_valeur_from_dico(self,layer,dico):
        list_sstype_valeur = []
        for cle , elements in dico.items():
            if cle == layer:
                for item in elements:
                     list_sstype_valeur.append((item.get("sous_type"),item.get("valeur")))
        # liste de tupples
        return list_sstype_valeur

    def get_icon_from_dico(self,layer,sous_type,valeur):
        elements = self.dico_layer_attrval.get(layer, [])
        for item in elements:
            if item.get("sous_type") == sous_type and item.get("valeur") == valeur:
                return item.get("icon", "")
        # Aucun match trouvé → retourne une chaîne vide
        return ""

    def get_nombtn_from_dico(self,layer,sous_type,valeur):
        elements = self.dico_layer_attrval.get(layer, [])
        for item in elements:
            if item.get("sous_type") == sous_type and item.get("valeur") == valeur:
                return item.get("nom_btn", "")
        # Aucun match trouvé → retourne une chaîne vide
        return ""

    def get_autre_val_from_dico(self,layer,sous_type,valeur):
        elements = self.dico_layer_attrval.get(layer, [])
        for item in elements:
            if item.get("sous_type") == sous_type and item.get("valeur") == valeur:
                return item.get("autre_valeur", "")
        # Aucun match trouvé → retourne une chaîne vide
        return ""

    def ajout_btn_from_json(self):
        self.liste_filtres = []
        for layer in self.dico_layer_attrval.keys():
            if layer == self.layer.name():
                champ_val = self.get_sstype_valeur_from_dico(self.layer.name(),self.dico_layer_attrval)
                for sstype,valeur in champ_val:
                    iconstr = self.get_icon_from_dico(self.layer.name(),sstype,valeur)
                    path_icon = os.path.join(self.path_repicon_btn, iconstr)
                    nom_json = self.get_nombtn_from_dico(self.layer.name(),sstype,valeur)
                    widget = QPushButton(valeur)
                    # stockage des infos dans le bouton (sstype, valeur)
                    widget.setProperty("sstype", sstype)
                    widget.setProperty("valeur", valeur)

                    # initialisation du filtre clic droit
                    filtre = FiltreClicDroit(self)
                    self.liste_filtres.append(filtre)
                    widget.installEventFilter(filtre)

                    # formatage du tooltip
                    autre_valeur = self.get_autre_val_from_dico(self.layer.name(),sstype,valeur)
                    text_tooltip = f"{sstype}{SEPARATION_TOOLTIP}{valeur}\n"
                    text_tooltip += self.format_tooltip(autre_valeur)

                    widget.setToolTip(text_tooltip)

                    # widget.setFixedWidth(button_width)
                    widget.setFixedHeight(20)

                    # si icon present dans json on affiche l'icon
                    # et on vide le nom du btn meme s'il est renseigné
                    if iconstr != "":
                        widget.setIcon(QIcon(path_icon))
                        widget.setText("")
                    else:
                        widget.setText(nom_json)

                    # connexion d'un evenement clic pour chaque btn
                    widget.clicked.connect(lambda checked, v=valeur, c=sstype: self.clic_btn(v, c))
                    self.layout_boutons.addWidget(widget)
                    # Recalcul dynamique de la taille du dialog
                    self.layout_boutons.invalidate()
                    self.layout_boutons.activate()
                    # astuce : attendre la fin de la boucle d'événement avant de recalculer la taille
                    QTimer.singleShot(0, self.dlg.adjustSize)

    #   formatage du tooltip avec valeur (str) + autre_valeur (liste)
    def format_tooltip(self,autre_valeur):
        tooltip = ""
        for attr,val in autre_valeur.items():
            tooltip += attr
            tooltip += SEPARATION_TOOLTIP
            tooltip += val
            tooltip += "\n"
        return tooltip

    def inittableview_autre_valeur(self):
        model = QStandardItemModel()
        model.setHorizontalHeaderLabels(["Sous type", "Valeur"])
        self.dlg_config_btn.tableView_autre_valeur.setModel(model)
        # tableview en lecture seule
        self.dlg_config_btn.tableView_autre_valeur.setEditTriggers(QAbstractItemView.NoEditTriggers)

        # selection de ligne entiere
        self.dlg_config_btn.tableView_autre_valeur.setSelectionBehavior(QTableView.SelectRows)
        self.dlg_config_btn.tableView_autre_valeur.setSelectionMode(QTableView.SingleSelection)

    def actualise_autre_val(self):
        # champ — val des "autres"
        sstype_autre = self.dlg_sel_champ_val_AUTRE.comboBoxchamps.currentText()
        attr_coche_autre = self.get_attrs_coches(self.dlg_sel_champ_val_AUTRE)

        # c'est le model qui gere les ajouts, donc on récupère le model associé a la tableview'
        model = self.dlg_config_btn.tableView_autre_valeur.model()

        # Suppression de toutes les lignes correspondant au sstype sélectionné
        # avant d'ajouter la ligne en cours.
        # Car on a droit qu'à une seule ligne de valeur
        # Parcourir les lignes en sens inverse (pour éviter le décalage d'index)
        for row in reversed(range(model.rowCount())):
            index = model.index(row, 0)  # 0 = première colonne
            valeur = model.data(index)
            if valeur == sstype_autre:
                model.removeRow(row)

        # si aucune valeur cochée, on n'ajoute rien
        if not attr_coche_autre:
            return

        # mise à jour du tableview avec la selection
        model.appendRow([QStandardItem(sstype_autre), QStandardItem(attr_coche_autre[0])])

        # sauvegarde dans le dico
        for item in self.dico_layer_attrval.get(self.layer.name(), []):
            # [0] car on ne prend que le premier de la liste vu qu'on peut avoir
            # qu'une seule valeur par sous type
            if item.get("sous_type") == self.sstype_btn_sel and item.get("valeur") == self.valeur_btn_sel:
                # Exemple : mise à jour de l'icône du bouton
                item["autre_valeur"] = self.convert_tableview_to_dico()
                break
        self.save_json()

    # renvoie le contenu du tableview des sstype-valeur sous forme de dictionnaire
    def convert_tableview_to_dico(self):
        model = self.dlg_config_btn.tableView_autre_valeur.model()
        data_dict = {}
        for row in range(model.rowCount()):
            # Première colonne : clé
            key = model.data(model.index(row, 0))
            # Deuxième colonne : valeur
            value = model.data(model.index(row, 1))

            if key:  # on évite les clés vides
                data_dict[key] = value

        return data_dict

    def actualise_btn(self):
        sstype = self.dlg_sel_champ_val.comboBoxchamps.currentText()
        valeurs = self.get_attrs_coches(self.dlg_sel_champ_val)

        # gestion des textedit : si le champ est de type textedit, on prend la valeur saisie
        # CAS TEXTEDIT
        if not valeurs:
            valeurs = []
            for i in range(self.dlg_sel_champ_val.listattributs.count()):
                item = self.dlg_sel_champ_val.listattributs.item(i)
                if item.flags() & Qt.ItemIsEditable:
                    valeurs.append(item.text())

        # Initialise la clé avec une liste vide si absente
        self.dico_layer_attrval.setdefault(self.layer.name(), [])
        champ_attr_a_suppr = {(sstype, attr) for attr in self.get_attrs_coches(self.dlg_sel_champ_val, False)}

        if self.layer.name() in self.dico_layer_attrval:
            self.dico_layer_attrval[self.layer.name()] = [
                item for item in self.dico_layer_attrval[self.layer.name()]
                if (item.get("sous_type"), item.get("valeur")) not in champ_attr_a_suppr
            ]

        for val in valeurs:
            # Vérifie si le tuple (sous_type, valeur) existe déjà dans les dict
            exists = any(
                item.get("sous_type") == sstype and item.get("valeur") == val
                for item in self.dico_layer_attrval[self.layer.name()]
            )
            if not exists:
                # Ajoute un dictionnaire complet avec valeurs par défaut
                self.dico_layer_attrval[self.layer.name()].append({
                    "sous_type": sstype,
                    "valeur": val,
                    "nom_btn": val,  # nom par défaut
                    "icon": "",
                    "autre_valeur": {}
                })

        # écriture du nouveau btn dans le json
        self.save_json()

        self.clear_layout(self.layout_boutons)
        self.liste_filtres = []
        self.initLayout()
        self.load_json()
        self.ajout_btn_from_json()

    def save_json(self):
        if not self.layer:
            return
        # Partir de l'ancien contenu si présent
        config = {}
        if os.path.exists(self.pathjson):
            try:
                with open(self.pathjson, "r", encoding="utf-8") as f:
                    config = json.load(f)
            except json.JSONDecodeError:
                print("Fichier JSON corrompu, un nouveau sera créé.")
                config = {}

        elements = []
        for item in self.dico_layer_attrval.get(self.layer.name(), []):
            sous_type = item.get("sous_type")
            valeur = item.get("valeur")
            nom_btn = item.get("nom_btn", "")
            icon = item.get("icon", "")
            autre_valeur = item.get("autre_valeur", {})

            elements.append({
                "sous_type": sous_type,
                "valeur": valeur,
                "nom_btn": nom_btn,
                "icon": icon,
                "autre_valeur": autre_valeur
            })

        # Mettre à jour seulement la couche courante
        config[self.layer.name()] = elements

        # Sauvegarde sur disque
        try:
            with open(self.pathjson, "w", encoding="utf-8") as f:
                json.dump(config, f, ensure_ascii=False, indent=2)
        except Exception as e:
            print(f"Erreur lors de la sauvegarde JSON : {e}")

    def load_json(self):
        if os.path.exists(self.pathjson):
            with open(self.pathjson, "r", encoding="utf-8") as f:
                data = json.load(f)
        else:
            print("Le fichier JSON n'existe pas.")
            return

        #  si on recupere bien un dictionnaire issu du json
        if not isinstance(data, dict):
            print("Format JSON incorrect : ce doit être un dictionnaire")
            return

        for layer_name, elements in data.items():
            if not isinstance(elements, list):
                print(f"La valeur pour {layer_name} n’est pas une liste.")
                continue

            cleaned_elements = []
            for item in elements:
                if not isinstance(item, dict):
                    print(f"Élément inattendu dans {layer_name} : {item}")
                    continue

                # On récupère proprement tous les champs attendus
                sous_type = item.get("sous_type", "")
                valeur = item.get("valeur", "")
                nom_btn = item.get("nom_btn", "")
                icon = item.get("icon", "")
                autre_valeur = item.get("autre_valeur", {}) or {}

                # On reconstruit un dict cohérent
                cleaned_item = {
                    "sous_type": sous_type,
                    "valeur": valeur,
                    "nom_btn": nom_btn,
                    "icon": icon,
                    "autre_valeur": autre_valeur
                }
                cleaned_elements.append(cleaned_item)

            # On stocke la liste d’éléments nettoyés dans le dico principal
            self.dico_layer_attrval[layer_name] = cleaned_elements

    def clic_btn(self,val,champ_courant):
        self.layer.startEditing()
        # changement : champs-valeur du bouton selectionné
        id_champ = self.layer.fields().indexFromName(champ_courant)
        for sel in self.layer.selectedFeatures():
            self.layer.changeAttributeValue(sel.id(), id_champ,val)

        # changement : champs-valeur des autres champ-valeur
        # tooltip = self.clicked_button.toolTip()
        # sstype, valeur = tooltip.split(SEPARATION_TOOLTIP)
        autre_sstype_valeur = {}
        # parcourt du dico pour ioler le dictionnaire des sstype_valeur à modifier
        for item in self.dico_layer_attrval.get(self.layer.name(), []):
            if item.get("sous_type") == champ_courant and item.get("valeur") == val:
                # Exemple : mise à jour du nom du bouton
                autre_sstype_valeur = item["autre_valeur"]
                break
        # changement d'attributs dans le layer
        for sel in self.layer.selectedFeatures():
            for champ,valeur in autre_sstype_valeur.items():
                id_champ = self.layer.fields().indexFromName(champ)
                self.layer.changeAttributeValue(sel.id(),id_champ,valeur)

    def on_active_layer_changed(self,layer):
        if not layer:
            self.layer = None
            return
        self.layer = layer

        JeuxAttributs.clear_layout(self.layout_boutons)
        self.initLayout()
        self.load_json()
        self.ajout_btn_from_json()

    def initGui(self):
        pass

    def unload(self):
        try:
            self.iface.layerTreeView().currentLayerChanged.disconnect(self.on_active_layer_changed)
        except TypeError:
            pass  # déjà déconnecté

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start:
            self.first_start = False

        # libère références Python aux anciennes UI (si elles existent)
        self.dlg = None
        self.dlg_sel_champ_val = None
        self.layout_boutons = None
        self.liste_filtres = []

        # chargement des ui
        self.dlg_sel_champ_val = QDialog()
        loadUi(os.path.join(os.path.dirname(__file__), "choix_widgets.ui"), self.dlg_sel_champ_val)
        self.dlg_sel_champ_val_AUTRE = QDialog()
        loadUi(os.path.join(os.path.dirname(__file__), "choix_widgets.ui"), self.dlg_sel_champ_val_AUTRE)
        self.dlg_config_btn = QDialog()
        loadUi(os.path.join(os.path.dirname(__file__), "conf_btn.ui"), self.dlg_config_btn)

        # connexion des slots : self.dlg_sel_champ_val
        self.dlg_sel_champ_val.pushButtonOk.clicked.connect(self.actualise_btn)
        self.dlg_sel_champ_val.comboBoxchamps.currentTextChanged.connect(
            lambda: self.change_champ(self.dlg_sel_champ_val))
        self.dlg_sel_champ_val_AUTRE.comboBoxchamps.currentTextChanged.connect(
            lambda: self.change_champ(self.dlg_sel_champ_val_AUTRE))
        self.dlg_sel_champ_val_AUTRE.pushButtonOk.clicked.connect(self.actualise_autre_val)
        self.dlg_sel_champ_val.pushButton_apropos.clicked.connect(self.on_apropos)

        # connexion des slots : self.dlg_config_btn
        # self.dlg_config_btn.pushButtonDeplacer.clicked.connect(self.deplace_btn)
        # gestion de la suppression de la ligne selectionnée (valeur autre)
        self.dlg_config_btn.pushButton_suppr_row.clicked.connect(self.suppr_ligne_tableview)
        self.dlg_config_btn.pushButtonOk.clicked.connect(
            lambda: self.valide_config_btn(self.sstype_btn_sel, self.valeur_btn_sel))
        self.dlg_config_btn.pushButton_choix_autre_valeur.clicked.connect(self.choix_autre_valeur)


        self.inittableview_autre_valeur()

        # show the dialog
        self.dlg = QDialog(self.iface.mainWindow())
        self.dlg.setWindowTitle("Jeux d'attributs")
        self.dlg.setWindowIcon(QIcon(os.path.join(os.path.dirname(__file__),"icons" ,"icon_principal.png")))
        self.dlg.setWindowFlags(Window | WindowCloseButtonHint)

        self.layer = self.iface.activeLayer()
        self.layout_boutons = LayoutFluide(self.dlg)

        self.dlg.setLayout(self.layout_boutons)

        self.initLayout()
        self.load_json()
        self.ajout_btn_from_json()

        # EVENEMENT DE CHANGEMENT DE LAYER ACTIF
        # s'assurer de ne pas connecter plusieurs fois
        try:
            self.iface.layerTreeView().currentLayerChanged.disconnect(self.on_active_layer_changed)
        except Exception:
            pass
        self.iface.layerTreeView().currentLayerChanged.connect(self.on_active_layer_changed)

        self.dlg.show()

