# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Complexe
                                 A QGIS plugin
 Assistant complexe
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-27
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Gérôme PECHEUR (IGN)
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QObject, QEvent, QTimer
from PyQt5.QtGui import QIcon, QPixmap, QStandardItem, QStandardItemModel
from PyQt5.QtWidgets import QDialog, QListWidgetItem, QPushButton, QFileDialog, QListView
from PyQt5.uic import loadUi
import json

# Initialize Qt resources from file resources.py
# Import the code for the dialog

SEPARATION_TOOLTIP = "\t\U0001F846\t"

import os.path
from .layout_fluide import *

class FiltreClicDroit(QObject):
    def __init__(self, class_parent):
        super().__init__()
        self.class_parent = class_parent

    def eventFilter(self,obj,event):
        if event.type() == QEvent.MouseButtonPress and event.button() == Qt.RightButton:
            self.class_parent.show_choix_icon(obj)
            return True  # on consomme l’événement (empêche le clic normal)
        return False

class JeuxAttributs():
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.dlg_choix_icon = None
        self.clicked_button = None
        self.datajson = None
        self.dlg = None
        self.iface = iface
        self.layer = None
        # self.layout = None
        self.dico_layer_attrval = {}
        self.liste_filtres = []
        self.model = None
        self.pathiconbtnclicked = None
        self.pathjson = os.path.join(os.path.dirname(__file__),"config", "config_btn.json")
        self.pathicon_config = os.path.join(os.path.dirname(__file__), "icons", "config.png")
        self.path_repicon_btn = os.path.join(os.path.dirname(__file__),"config", "icons_btn")

        self.layout_boutons = None

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None


    def show_choix_icon(self,btn):
        self.clicked_button = btn
        # recuperation des infos du boutons cliqué grace au tooltip qui contient : sstype, valeur
        tooltip = self.clicked_button.toolTip()
        sstype, valeur = tooltip.split(SEPARATION_TOOLTIP)

        self.dlg_choix_icon = QDialog()
        loadUi(os.path.join(os.path.dirname(__file__), "choix_icon.ui"), self.dlg_choix_icon)
        self.dlg_choix_icon.setWindowTitle("Paramétrage des boutons et des actions associés")
        self.dlg_choix_icon.setWindowFlags(Qt.WindowStaysOnTopHint | Qt.WindowCloseButtonHint)
        self.init_listview_icones()
        self.dlg_choix_icon.lineEditNomBtn.setText(self.clicked_button.text())

        sstype_str = f"<span style='color: red'><b>{sstype}</b></span>"
        self.dlg_choix_icon.label_ss_type.setText(sstype_str)
        valeur_str = f"<span style='color: red'><b>{valeur}</b></span>"
        self.dlg_choix_icon.label_valeur.setText(valeur_str)
        self.dlg_choix_icon.label_fleche.setText(SEPARATION_TOOLTIP)

        self.dlg_choix_icon.radioButtonText.setChecked(True)
        self.dlg_choix_icon.labelAvertissement.setText("")
        self.dlg_choix_icon.show()
        self.dlg_choix_icon.pushButtonOk.clicked.connect(self.valide_config_btn)

    def valide_config_btn(self):
        if self.dlg_choix_icon.radioButtonText.isChecked():
            if self.dlg_choix_icon.lineEditNomBtn.text() == "":
                self.dlg_choix_icon.labelAvertissement.setText("<span style='color: red'><b>Le nom du bouton est vide</b></span>")
                return
            self.clicked_button.setText(self.dlg_choix_icon.lineEditNomBtn.text())
            self.clicked_button.setIcon(QIcon())
            self.clicked_button.adjustSize()

        elif self.dlg_choix_icon.radioButtonIcon.isChecked():
            if self.pathiconbtnclicked is None:
                self.dlg_choix_icon.labelAvertissement.setText(
                    "<span style='color: red'><b>Aucune icône n'est sélectionnée</b></span>")
                return
            self.clicked_button.setText("")
            self.clicked_button.setIcon(QIcon(self.pathiconbtnclicked))
            # self.clicked_button.setFixedWidth(20)
        self.dlg_choix_icon.close()

    def init_listview_icones(self):
        self.model = QStandardItemModel()
        self.dlg_choix_icon.listViewIcone.setModel(self.model)
        self.dlg_choix_icon.listViewIcone.setViewMode(QListView.IconMode)
        self.dlg_choix_icon.listViewIcone.setSelectionMode(QListView.SingleSelection)
        for filename in os.listdir(self.path_repicon_btn):
            if filename.lower().endswith(".ico"):
                path = os.path.join(self.path_repicon_btn, filename)
                # pixmap = QPixmap(path).scaled(30, 30)
                pixmap = QPixmap(path)
                icon = QIcon(pixmap)

                item = QStandardItem(icon, filename)
                item.setData(path)  # On garde le chemin complet
                item.setEditable(False)
                self.model.appendRow(item)

        self.dlg_choix_icon.listViewIcone.clicked.connect(self.get_icon_path_selected)

    def get_icon_path_selected(self, index):
        """Quand l'utilisateur clique sur une icône."""
        self.pathiconbtnclicked = self.model.itemFromIndex(index).data()
        # self.clicked_button.setText("")
        # self.clicked_button.setIcon(QIcon(path))
        # self.clicked_button.setFixedWidth(20)


    # ajout de tous les champs possible dans le combobox
    def init_combo_choix_champ(self):
        self.layer = self.iface.activeLayer()
        for field in self.layer.fields():
            index = self.layer.fields().indexOf(field.name())
            widget_type = self.get_type_champ(index)
            if widget_type == "ValueMap":
                self.dlg_selattributs.comboBoxchamps.addItem(field.name())

    # initialise toutes les valeurs en fonction du champ sélectionné
    def init_list_valeur(self,champ):
        # pk faire ce test !!
        if champ == "":
            return

        list_sstype_val = self.get_sstype_valeur_from_dico(self.layer.name(),self.dico_layer_attrval)

        self.dlg_selattributs.listattributs.clear()

        layer_field = self.layer.fields().field(champ)
        # Vérifier le type d’éditeur
        editor_setup = layer_field.editorWidgetSetup()
        valeurs_possibles = []
        for v in editor_setup.config().values():
            # cas de liste de dictionnaire -> on de-pile
            if isinstance(v, dict):
                valeurs_possibles.extend(v.values())  # récupérer les vrais libellés
            else:
                valeurs_possibles.append(v)

        for val in valeurs_possibles:
            item = QListWidgetItem(val)
            item.setCheckState(Qt.Unchecked)
            if (champ,val) in list_sstype_val:
                item.setCheckState(Qt.Checked)
            self.dlg_selattributs.listattributs.addItem(item)

    def get_attrs_coches(self,coche = True):
        val_coche = []
        if coche:
            bcoche = Qt.Checked
        else:
            bcoche = Qt.Unchecked
        for i in range(self.dlg_selattributs.listattributs.count()):
            item = self.dlg_selattributs.listattributs.item(i)
            if item.checkState() == bcoche:
                val_coche.append(item.text())
        return val_coche

    def show_choix_attr_val(self):
        self.dlg_selattributs.comboBoxchamps.clear()
        self.dlg_selattributs.listattributs.clear()
        self.init_combo_choix_champ()
        self.dlg_selattributs.setWindowFlags(Qt.WindowStaysOnTopHint | Qt.WindowCloseButtonHint)
        self.dlg_selattributs.exec_()

    def change_champ(self):
        self.dlg_selattributs.listattributs.clear()
        champ = self.dlg_selattributs.comboBoxchamps.currentText()
        self.init_list_valeur(champ)

    def get_type_champ(self,index):
        return self.layer.editorWidgetSetup(index).type()

    @staticmethod
    def clear_layout(layout):
        """Supprime tous les widgets d’un QLayout"""
        while layout.count():
            item = layout.takeAt(0)
            widget = item.widget()
            if widget is not None:
                widget.setParent(None)
                widget.deleteLater()
            elif item.layout():
                JeuxAttributs.clear_layout(item.layout())

    # ajout du bouton de paramétrage
    def initLayout(self):

        self.btn_add = QPushButton()
        self.btn_add.setIcon(QIcon(self.pathicon_config))
        self.btn_add.setFixedWidth(20)
        self.btn_add.setFixedHeight(20)
        # self.btn_add.setStyleSheet("background-color: lightblue;")
        self.btn_add.clicked.connect(self.show_choix_attr_val)

        self.layout_boutons.addWidget(self.btn_add)

        self.dlg.setLayout(self.layout_boutons)
        # self.dlg.adjustSize()
        # self.dlg.updateGeometry()
        # Connecte l’événement de redimensionnement

    def get_sstype_valeur_from_dico(self,layer,dico):
        list_sstype_valeur = []
        for cle , elements in dico.items():
            if cle == layer:
                for item in elements:
                     list_sstype_valeur.append((item.get("sous_type"),item.get("valeur")))
        # liste de tupples
        return list_sstype_valeur

    def get_icon_from_dico(self,layer,sous_type,valeur):
        elements = self.dico_layer_attrval.get(layer, [])
        for item in elements:
            if item.get("sous_type") == sous_type and item.get("valeur") == valeur:
                return item.get("icon", "")
        # Aucun match trouvé → retourne une chaîne vide
        return ""

    def get_nombtn_from_dico(self,layer,sous_type,valeur):
        elements = self.dico_layer_attrval.get(layer, [])
        for item in elements:
            if item.get("sous_type") == sous_type and item.get("valeur") == valeur:
                return item.get("nom_btn", "")
        # Aucun match trouvé → retourne une chaîne vide
        return ""

    def ajout_btn_from_json(self):
        self.liste_filtres = []
        for layer in self.dico_layer_attrval.keys():
            if layer == self.layer.name():
                champ_val = self.get_sstype_valeur_from_dico(self.layer.name(),self.dico_layer_attrval)
                for sstype,valeur in champ_val:
                    iconstr = self.get_icon_from_dico(self.layer.name(),sstype,valeur)
                    path_icon = os.path.join(self.path_repicon_btn, iconstr)
                    nom_json = self.get_nombtn_from_dico(self.layer.name(),sstype,valeur)
                    widget = QPushButton(valeur)
                    # initialisation du filtre clic droit
                    filtre = FiltreClicDroit(self)
                    self.liste_filtres.append(filtre)
                    widget.installEventFilter(filtre)

                    # widget.setToolTip(f"{sstype}\t\U0001F846\t{valeur}")
                    widget.setToolTip(f"{sstype}{SEPARATION_TOOLTIP}{valeur}")

                    # widget.setFixedWidth(button_width)
                    widget.setFixedHeight(20)

                    # si icon present dans json on affiche l'icon
                    # et on vide le nom du btn meme s'il est renseigné
                    if iconstr != "":
                        widget.setIcon(QIcon(path_icon))
                        widget.setText("")
                    else:
                        widget.setText(nom_json)

                    # connexion d'un evenement clic pour chaque btn
                    widget.clicked.connect(lambda checked, v=valeur, c=sstype: self.clic_btn(v, c))
                    self.layout_boutons.addWidget(widget)
                    # Recalcul dynamique de la taille du dialog
                    self.layout_boutons.invalidate()
                    self.layout_boutons.activate()
                    # astuce : attendre la fin de la boucle d'événement avant de recalculer la taille
                    QTimer.singleShot(0, self.dlg.adjustSize)


    def actualise_btn(self):
        sstype = self.dlg_selattributs.comboBoxchamps.currentText()
        valeurs = self.get_attrs_coches()

        # Initialise la clé avec une liste vide si absente
        self.dico_layer_attrval.setdefault(self.layer.name(), [])
        champ_attr_a_suppr = {(sstype, attr) for attr in self.get_attrs_coches(False)}

        if self.layer.name() in self.dico_layer_attrval:
            self.dico_layer_attrval[self.layer.name()] = [
                item for item in self.dico_layer_attrval[self.layer.name()]
                if (item.get("sous_type"), item.get("valeur")) not in champ_attr_a_suppr
            ]

        for val in valeurs:
            # Vérifie si le tuple (sous_type, valeur) existe déjà dans les dict
            exists = any(
                item.get("sous_type") == sstype and item.get("valeur") == val
                for item in self.dico_layer_attrval[self.layer.name()]
            )
            if not exists:
                # Ajoute un dictionnaire complet avec valeurs par défaut
                self.dico_layer_attrval[self.layer.name()].append({
                    "sous_type": sstype,
                    "valeur": val,
                    "nom_btn": val,  # nom par défaut
                    "icon": "",
                    "autre_valeur": {}
                })

        # écriture du nouveau btn dans le json
        self.save_json()

        self.clear_layout(self.layout_boutons)
        self.liste_filtres = []
        self.initLayout()
        self.load_json()
        self.ajout_btn_from_json()

    def save_json(self):
        if not self.layer:
            return
        # Partir de l'ancien contenu si présent
        config = {}
        if os.path.exists(self.pathjson):
            try:
                with open(self.pathjson, "r", encoding="utf-8") as f:
                    config = json.load(f)
            except json.JSONDecodeError:
                print("Fichier JSON corrompu, un nouveau sera créé.")
                config = {}
        elements = []

        for item in self.dico_layer_attrval.get(self.layer.name(), []):
            sous_type = item.get("sous_type")
            valeur = item.get("valeur")
            nom_btn = item.get("nom_btn", "")
            icon = item.get("icon", "")
            autre_valeur = item.get("autre_valeur", {})

            # Compléter depuis l'ancien JSON si présent
            if self.datajson and self.datajson.data:
                for old_item in self.datajson.data.get(self.layer.name(), []):
                    if old_item["sous_type"] == sous_type and old_item["valeur"] == valeur:
                        icon = old_item.get("icon", icon)
                        autre_valeur = old_item.get("autre_valeur", autre_valeur)
                        nom_btn = old_item.get("nom_btn", nom_btn)
                        break

            elements.append({
                "sous_type": sous_type,
                "valeur": valeur,
                "nom_btn": nom_btn,
                "icon": icon,
                "autre_valeur": autre_valeur
            })

        # Mettre à jour seulement la couche courante
        config[self.layer.name()] = elements

        # Sauvegarde sur disque
        try:
            with open(self.pathjson, "w", encoding="utf-8") as f:
                json.dump(config, f, ensure_ascii=False, indent=2)
        except Exception as e:
            print(f"Erreur lors de la sauvegarde JSON : {e}")

    def load_json(self):
        # self.datajson = JsonRead()
        # data = self.datajson.charger_json(self.pathjson)
        with open(self.pathjson, "r", encoding="utf-8") as f:
            data = json.load(f)

        #  si c'est un recupere bien un dictionnaire issu du json
        if not isinstance(data, dict):
            print("Format JSON incorrect : ce doit être un dictionnaire")
            return

        for layer_name, elements in data.items():
            if not isinstance(elements, list):
                print(f"La valeur pour {layer_name} n’est pas une liste.")
                continue

            cleaned_elements = []
            for item in elements:
                if not isinstance(item, dict):
                    print(f"Élément inattendu dans {layer_name} : {item}")
                    continue

                # On récupère proprement tous les champs attendus
                sous_type = item.get("sous_type", "")
                valeur = item.get("valeur", "")
                nom_btn = item.get("nom_btn", "")
                icon = item.get("icon", "")
                autre_valeur = item.get("autre_valeur", {}) or {}

                # On reconstruit un dict cohérent
                cleaned_item = {
                    "sous_type": sous_type,
                    "valeur": valeur,
                    "nom_btn": nom_btn,
                    "icon": icon,
                    "autre_valeur": autre_valeur
                }
                cleaned_elements.append(cleaned_item)

            # On stocke la liste d’éléments nettoyés dans le dico principal
            self.dico_layer_attrval[layer_name] = cleaned_elements

    def clic_btn(self,val,champ_courant):
        print(f"CLIC BOUTON ,champ courant - val = {champ_courant}-{val}")
        self.layer.startEditing()
        id_champ = self.layer.fields().indexFromName(champ_courant)
        for sel in self.layer.selectedFeatures():
            self.layer.changeAttributeValue(sel.id(), id_champ,val)

    def on_active_layer_changed(self,layer):
        print("on_active_layer_changed")
        if not layer:
            self.layer = None
            return
        self.layer = layer

        JeuxAttributs.clear_layout(self.layout_boutons)
        self.initLayout()
        self.load_json()
        self.ajout_btn_from_json()


    def importer(self):
        fichier, _ = QFileDialog.getOpenFileName(None,
            "Sélectionner un fichier 'config.json'",
            os.path.join(os.path.dirname(__file__)),"Fichier json (*.json)")

    def exporter(self):
        dossier = QFileDialog.getExistingDirectory(None,
        "Sélectionner un répertoire de sauvegarde de la configuration")

    def initGui(self):
        pass


    def unload(self):
        try:
            self.iface.layerTreeView().currentLayerChanged.disconnect(self.on_active_layer_changed)
        except TypeError:
            pass  # déjà déconnecté

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start:
            self.first_start = False

        # libère références Python aux anciennes UI (si elles existent)
        self.dlg = None
        self.dlg_selattributs = None
        self.layout_boutons = None
        self.liste_filtres = []

        self.dlg_selattributs = QDialog()
        loadUi(os.path.join(os.path.dirname(__file__), "choix_widgets.ui"), self.dlg_selattributs)

        # show the dialog
        self.dlg = QDialog()
        self.dlg.setWindowTitle("Jeux d'attributs")
        self.dlg.setWindowIcon(QIcon(os.path.join(os.path.dirname(__file__),"icons" ,"icon_principal.png")))
        self.dlg.setWindowFlags(Qt.WindowStaysOnTopHint | Qt.WindowCloseButtonHint)

        self.layer = self.iface.activeLayer()
        self.layout_boutons = LayoutFluide(self.dlg)
        self.initLayout()
        self.load_json()
        self.ajout_btn_from_json()

        # EVENEMENT DE CHANGEMENT DE LAYER ACTIF
        # s'assurer de ne pas connecter plusieurs fois
        try:
            self.iface.layerTreeView().currentLayerChanged.disconnect(self.on_active_layer_changed)
        except Exception:
            pass
        self.iface.layerTreeView().currentLayerChanged.connect(self.on_active_layer_changed)

        # événement du dialog de choix des champs
        self.dlg_selattributs.pushButtonOk.clicked.connect(self.actualise_btn)
        self.dlg_selattributs.pushButtonImporter.clicked.connect(self.importer)
        self.dlg_selattributs.pushButtonExporter.clicked.connect(self.exporter)
        self.dlg_selattributs.comboBoxchamps.currentTextChanged.connect(self.change_champ)

        self.dlg.show()

