# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Complexe
                                 A QGIS plugin
 Assistant complexe
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-27
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Gérôme PECHEUR (IGN)
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import Qt, QTimer, QObject, QEvent
from PyQt5.QtGui import QIcon, QPixmap, QStandardItem, QStandardItemModel
from PyQt5.QtWidgets import QDialog, QListWidgetItem, QComboBox, QGridLayout, QPushButton, QTextEdit, QWidget, \
    QMessageBox, QVBoxLayout, QFileDialog, QListView
from PyQt5.uic import loadUi
import json


# Initialize Qt resources from file resources.py
# Import the code for the dialog
# from .jeux_attributs_dialog import JeuxAttributsDialog
import os.path


class FiltreClicDroit(QObject):
    def __init__(self, class_parent):
        super().__init__()
        self.class_parent = class_parent

    def eventFilter(self, obj, event):
        if event.type() == QEvent.MouseButtonPress and event.button() == Qt.RightButton:
            # QMessageBox.information(None, "Clic droit", f"Clic droit sur {obj.text()} 👇")

            self.class_parent.show_choix_icon(obj)
            return True  # on consomme l’événement (empêche le clic normal)
        return False


class JeuxAttributs:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.dlg = None
        self.iface = iface
        self.layer = None
        self.layout = None
        self.dico_layer_attrval = {}
        self.liste_filtres = []
        self.model = None
        self.pathiconbtnclicked = None
        self.pathjson = os.path.join(os.path.dirname(__file__), "config_btn.json")
        self.pathicon = os.path.join(os.path.dirname(__file__), "icons", "config.png")

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None


    def show_choix_icon(self,btn):
        self.clicked_button = btn
        self.dlg_choix_icon = QDialog()
        loadUi(os.path.join(os.path.dirname(__file__), "choix_icon.ui"), self.dlg_choix_icon)
        self.dlg_choix_icon.setWindowFlags(Qt.WindowStaysOnTopHint | Qt.WindowCloseButtonHint)
        self.init_listview_icones()
        self.dlg_choix_icon.lineEditNomBtn.setText(self.clicked_button.text())
        self.dlg_choix_icon.radioButtonText.setChecked(True)
        self.dlg_choix_icon.labelAvertissement.setText("")
        self.dlg_choix_icon.show()
        # fichier, _ = QFileDialog.getOpenFileName(
        #     None,
        #     "Sélectionner une icône",
        #     os.path.join(os.path.dirname(__file__), "icons_btn"),
        #     "Images (*.png)"
        # )
        # # TODO definir des property pour chaques btn crées pour sauvegarder ici l'icon associé
        # obj.setIcon(QIcon(fichier))
        # self.dlg_choix_icon.pushButtonOk.clicked.connect(self.dlg_choix_icon.close)
        self.dlg_choix_icon.pushButtonOk.clicked.connect(self.valide_config_btn)

    def valide_config_btn(self):
        print(self.pathiconbtnclicked)
        if self.dlg_choix_icon.radioButtonText.isChecked():
            if self.dlg_choix_icon.lineEditNomBtn.text() == "":
                self.dlg_choix_icon.labelAvertissement.setText("<span style='color: red'><b>Le nom du bouton est vide</b></span>")
                return
            self.clicked_button.setText(self.dlg_choix_icon.lineEditNomBtn.text())
            self.clicked_button.setIcon(QIcon())
            self.clicked_button.adjustSize()

        elif self.dlg_choix_icon.radioButtonIcon.isChecked():
            if self.pathiconbtnclicked == None:
                self.dlg_choix_icon.labelAvertissement.setText(
                    "<span style='color: red'><b>Aucune icône est sélectionnée</b></span>")
                return
            self.clicked_button.setText("")
            self.clicked_button.setIcon(QIcon(self.pathiconbtnclicked))
            # self.clicked_button.setFixedWidth(20)
        self.dlg_choix_icon.close()

    def init_listview_icones(self):
        path_repicon = os.path.join(os.path.dirname(__file__), "icons_btn")
        """Charge les images PNG du dossier dans la QListView."""
        self.model = QStandardItemModel()
        self.dlg_choix_icon.listViewIcone.setModel(self.model)
        self.dlg_choix_icon.listViewIcone.setViewMode(QListView.IconMode)
        self.dlg_choix_icon.listViewIcone.setSelectionMode(QListView.SingleSelection)
        for filename in os.listdir(path_repicon):
            if filename.lower().endswith(".ico"):
                path = os.path.join(path_repicon, filename)
                # pixmap = QPixmap(path).scaled(30, 30)
                pixmap = QPixmap(path)
                icon = QIcon(pixmap)

                item = QStandardItem(icon, filename)
                item.setData(path)  # On garde le chemin complet
                item.setEditable(False)
                self.model.appendRow(item)

        self.dlg_choix_icon.listViewIcone.clicked.connect(self.get_icon_path_selected)

    def get_icon_path_selected(self, index):
        """Quand l'utilisateur clique sur une icône."""
        self.pathiconbtnclicked = self.model.itemFromIndex(index).data()
        # self.clicked_button.setText("")
        # self.clicked_button.setIcon(QIcon(path))
        # self.clicked_button.setFixedWidth(20)


    # ajout de tous les champs possible dans le combobox
    def init_combo_choix_champ(self):
        self.layer = self.iface.activeLayer()
        for field in self.layer.fields():
            index = self.layer.fields().indexOf(field.name())
            widget_type = self.get_type_champ(index)
            if widget_type == "ValueMap":
                self.dlg_selattributs.comboBoxchamps.addItem(field.name())

    # initialise toutes les valeurs en fonction du champ sélectionné
    def init_list_valeur(self,champ):
        # pk faire ce test !!
        if champ == "":
            return
        list_att = []
        if self.layer.name() in self.dico_layer_attrval:
            for tmp, attr in self.dico_layer_attrval[self.layer.name()]:
                list_att.append(attr)

        # comparaison avec self.dlg_selattributs.listattributs pour cocher ce qu'il y a en commun
        self.dlg_selattributs.listattributs.clear()

        layer_field = self.layer.fields().field(champ)
        # Vérifier le type d’éditeur
        editor_setup = layer_field.editorWidgetSetup()
        valeurs_possibles = []
        for v in editor_setup.config().values():
            # cas de liste de dictionnaire -> on de-pile
            if isinstance(v, dict):
                valeurs_possibles.extend(v.values())  # récupérer les vrais libellés
            else:
                valeurs_possibles.append(v)

        for val in valeurs_possibles:
            item = QListWidgetItem(val)
            item.setCheckState(Qt.Unchecked)
            if val in list_att:
                item.setCheckState(Qt.Checked)
                # print(val)
            self.dlg_selattributs.listattributs.addItem(item)

    def get_attrs_coches(self,coche = True):
        val_coche = []
        if coche:
            bcoche = Qt.Checked
        else:
            bcoche = Qt.Unchecked
        for i in range(self.dlg_selattributs.listattributs.count()):
            item = self.dlg_selattributs.listattributs.item(i)
            if item.checkState() == bcoche:
                val_coche.append(item.text())
        return val_coche

    def show_choix_attr_val(self):
        self.dlg_selattributs.comboBoxchamps.clear()
        self.dlg_selattributs.listattributs.clear()
        self.init_combo_choix_champ()
        self.dlg_selattributs.setWindowFlags(Qt.WindowStaysOnTopHint | Qt.WindowCloseButtonHint)
        self.dlg_selattributs.exec_()

    def change_champ(self):
        # print("change_champ")
        self.dlg_selattributs.listattributs.clear()
        champ = self.dlg_selattributs.comboBoxchamps.currentText()
        self.init_list_valeur(champ)

    def get_type_champ(self,index):
        return self.layer.editorWidgetSetup(index).type()

    @staticmethod
    def clear_layout(layout):
        """Supprime tous les widgets d’un QLayout."""
        while layout.count():
            item = layout.takeAt(0)
            widget = item.widget()
            if widget is not None:
                widget.setParent(None)
                widget.deleteLater()
            elif item.layout():
                JeuxAttributs.clear_layout(item.layout())

    def initLayout(self):
        # Bouton fixe (ligne 0)
        # pathicon = os.path.join(os.path.dirname(__file__),"icons", "config.png")

        self.btn_add = QPushButton()
        self.btn_add.setIcon(QIcon(self.pathicon))
        self.btn_add.setFixedWidth(20)
        self.btn_add.setFixedHeight(20)
        # self.btn_add.setStyleSheet("background-color: lightblue;")
        self.btn_add.clicked.connect(self.show_choix_attr_val)

        # self.layout.setContentsMargins(5, 0, 0, 0)
        self.layout.setVerticalSpacing(0)
        self.layout.setHorizontalSpacing(0)

        self.layout.addWidget(self.btn_add, 0, 0, 1, 1, Qt.AlignLeft)
        # print("btn existant1 = ",self.layout.count())

        self.dlg.setLayout(self.layout)
        self.dlg.adjustSize()
        # Connecte l’événement de redimensionnement
        # self.dlg.resizeEvent = self.on_resize

        # Premier affichage différé
        # QTimer.singleShot(0, self.ajout_btn)

    def ajout_btn_from_json(self):
        button_width = 50
        largeur_limite = 500
        boutons_existants = self.layout.count()
        # Calculer combien de boutons par ligne avant de passer à la suivante
        boutons_par_ligne = max(1, largeur_limite // button_width)

        self.liste_filtres = []
        for layer,champ_val in self.dico_layer_attrval.items():
            if layer == self.layer.name():
                for i,(champ,valeur) in enumerate(champ_val):
                    # print(f"champ = {champ} , valeur = {valeur}")
                    # self.dlg.resize(self.dlg.width()+i*100,self.dlg.height())
                    widget = QPushButton(valeur)
                    # inistallation du filtre clic droit
                    filtre = FiltreClicDroit(self)
                    self.liste_filtres.append(filtre)
                    widget.installEventFilter(filtre)


                    widget.setToolTip(f"{champ}\t\U0001F846\t{valeur}")
                    # widget.setFixedWidth(button_width)
                    widget.setFixedHeight(20)
                    index = boutons_existants -1 + i # "-1" car le bouton "Choisir" est à (0,0)
                    row = index // boutons_par_ligne
                    col = (index % boutons_par_ligne) +1

                    self.layout.addWidget(widget, row, col)

                    # connexion d'un evenement clic pour chaque btn
                    widget.clicked.connect(lambda checked, v=valeur, c=champ: self.clic_btn(v, c))
        self.dlg.adjustSize()

    def actualise_btn(self):
        print("actualise_btn")

        champ_courant = self.dlg_selattributs.comboBoxchamps.currentText()
        valeurs = self.get_attrs_coches()

        # liste_tuple_champ_attr_abs = []
        # for attr in self.get_attrs_coches(False):
        #     liste_tuple_champ_attr_abs.append((champ_courant,attr))
        # self.dico_layer_attrval[self.layer.name()] = [
        #     item for item in self.dico_layer_attrval[self.layer.name()]
        #     if item not in liste_tuple_champ_attr_abs
        # ]

        # Initialise la clé avec une liste vide si absente
        self.dico_layer_attrval.setdefault(self.layer.name(), [])

        champ_attr_a_suppr = {(champ_courant, attr) for attr in self.get_attrs_coches(False)}
        # Vérifie que la clé existe avant de filtrer
        if self.layer.name() in self.dico_layer_attrval:
            self.dico_layer_attrval[self.layer.name()] = [
                item for item in self.dico_layer_attrval[self.layer.name()]
                if item not in champ_attr_a_suppr
            ]
        # ajout du btn dans le dictionnaire
        for val in valeurs:
            tuple_champ_val = (champ_courant, val)
            if tuple_champ_val not in self.dico_layer_attrval[self.layer.name()]:
                self.dico_layer_attrval[self.layer.name()].append(tuple_champ_val)

        # écriture du nouveau btn dans le json
        self.save_json()

        # chargement a partir du json
        self.clear_layout(self.layout)
        self.initLayout()
        self.load_json()
        self.ajout_btn_from_json()

    def save_json(self):
        print("save_json")
        """Sauvegarde la configuration des boutons associés à chaque champ."""
        # path = os.path.join(os.path.dirname(__file__), "config.json")
        # Charger la config existante pour la mettre à jour proprement
        if os.path.exists(self.pathjson):
            try:
                with open(self.pathjson, "r", encoding="utf-8") as f:
                    config = json.load(f)
            except json.JSONDecodeError:
                config = {}
        else:
            config = {}
        # Mise à jour de la configuration du layer courant
        if self.layer:
            config[self.layer.name()] = self.dico_layer_attrval[self.layer.name()]

        # Écriture dans le fichier
        with open(self.pathjson, "w", encoding="utf-8") as f:
            json.dump(config, f, indent=4, ensure_ascii=False)

    def load_json(self):
        """Charge la configuration enregistrée pour le layer courant et recrée les boutons."""
        # path = os.path.join(os.path.dirname(__file__), "config.json")

        if not os.path.exists(self.pathjson):
            return
        try:
            with open(self.pathjson, "r", encoding="utf-8") as f:
                config = json.load(f)
        except json.JSONDecodeError:
            return
        if not self.layer:
            return
        layer_name = self.layer.name()
        if layer_name not in config:
            return
        # Charger la liste de couples [(champ, valeur), ...]
        # self.champ_attr_sel = config[layer_name]
        self.dico_layer_attrval = {
            key: [tuple(p) for p in pairs] if pairs else []
            for key, pairs in config.items()
        }
        self.dlg.adjustSize()


    def clic_btn(self,val,champ_courant):
        print(f"CLIC BOUTON ,champ courant - val = {champ_courant}-{val}")
        self.layer.startEditing()
        id_champ = self.layer.fields().indexFromName(champ_courant)
        for sel in self.layer.selectedFeatures():
            self.layer.changeAttributeValue(sel.id(), id_champ,val)

    def on_active_layer_changed(self,layer):
        if layer:
            self.layer = layer
            JeuxAttributs.clear_layout(self.layout)
            self.initLayout()
            self.load_json()
            self.ajout_btn_from_json()
        else:
            self.layer = None

    def importer(self):
        print("importer")
        fichier, _ = QFileDialog.getOpenFileName(
            None,
            "Sélectionner un fichier 'config.json'",
            os.path.join(os.path.dirname(__file__)),
            "Fichier json (*.json)"
        )

    def exporter(self):
        print("Exporter")
        dossier = QFileDialog.getExistingDirectory(
            None,
            "Sélectionner un répertoire de sauvegarde de la configuration"
        )

    def initGui(self):
        pass
        """Create the menu entries and toolbar icons inside the QGIS GUI."""


    def unload(self):
        try:
            self.iface.layerTreeView().currentLayerChanged.disconnect(self.on_active_layer_changed)
        except TypeError:
            pass  # déjà déconnecté

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start:
            self.first_start = False
            # self.dlg = JeuxAttributsDialog()

        self.dlg_selattributs = QDialog()
        loadUi(os.path.join(os.path.dirname(__file__), "choix_widgets.ui"), self.dlg_selattributs)

        # show the dialog
        self.dlg = QDialog()
        self.dlg.setWindowTitle("Jeux d'attributs")
        self.dlg.setWindowIcon(QIcon(os.path.join(os.path.dirname(__file__),"icons" ,"icon_principal.png")))
        self.dlg.setWindowFlags(Qt.WindowStaysOnTopHint | Qt.WindowCloseButtonHint)

        self.layout = QGridLayout()

        self.layer = self.iface.activeLayer()
        self.initLayout()
        self.load_json()
        self.ajout_btn_from_json()

        # EVENEMENT DE CHANGEMENT DE LAYER ACTIF
        self.iface.layerTreeView().currentLayerChanged.connect(self.on_active_layer_changed)
        # événement dialog principal
        # self.btn_selchamp.clicked.connect(self.show_choix_attr_val)

        # événement du dialog de choix des champs
        # self.dlg_selattributs.pushButtonOk.clicked.connect(self.ajout_btn)
        self.dlg_selattributs.pushButtonOk.clicked.connect(self.actualise_btn)
        self.dlg_selattributs.pushButtonImporter.clicked.connect(self.importer)
        self.dlg_selattributs.pushButtonExporter.clicked.connect(self.exporter)

        self.dlg_selattributs.comboBoxchamps.currentTextChanged.connect(self.change_champ)

        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result == QDialog.Rejected:
            # self.save_json()
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
